### ISSUE TITLE
Doesn't work with unified diff format [PATCH]

### ISSUE THREAD

**Issue by timbunce** [l0b0/diff-ignore-moved-lines#5]
The diff_lines expression doesn't account for the fact that unified diffs don't have a space after the leading `+` or `-`. A simple fix is to put the sed first so the grep only has to consider `>` and '<':
```
--- a/diff-ignore-moved-lines.sh
+++ b/diff-ignore-moved-lines.sh
@@ -43,3 +43,3 @@ set -o errexit -o noclobber -o nounset -o pipefail
 # Also, convert unified diffs to "normal" diffs
-diff_lines="$(grep '^[><+-] ' | sed 's/^+/>/;s/^-/</')" || exit 0
+diff_lines="$(sed 's/^+/> /;s/^-/< /' | grep '^[><]')" || exit 0
```
Extending the test suite to cover this would be good.

It also occurs to me that the grep could be removed if the sed script was extended to discard lines that don't match `^[><]`. Given that diff_lines is invoked a lot that would probably give a useful speed boost on large diffs.

**Comment by l0b0** [comment]
Thank you for the tip!
